### PR TITLE
Add 128-bit support

### PR DESCRIPTION
**Pull request by petoknm**

### CODE REVIEW

**Comment by petoknm** [comment]
@EugeneGonzalez Can you please take a look at this? I am using this for one of my projects and I think it might be useful to others as well. Maybe we will need to put it behind a feature flag.

**Comment by EugeneGonzalez** [comment]
Sorry about missing this, this all looks good to me. I would prefer adding 128-bit support behind a feature flag due to this library predating its introduction.

**Comment by petoknm** [comment]
I added the feature gate, mentioned 128bit support in the readme and added benchmarks.

**Comment by EugeneGonzalez** [comment]
LGTM, thanks for the PR.

**Pull request merged**
